package dddhexagonalworkshop.conference.attendees.persistence;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class AttendeeEntityTest {

    @Test
    public void testAttendeeEntityCreation() {
        String email = "aragorn@arnor.gov";
        AttendeeEntity attendeeEntity = new AttendeeEntity(email);

        assertNotNull(attendeeEntity, "AttendeeEntity should not be null");
        assertEquals(email, attendeeEntity.getEmail(), "Email should match");
    }

    @Test
    public void testGetId() {
        String email = "aragorn@arnor.gov";
        AttendeeEntity attendeeEntity = new AttendeeEntity(email);

        // ID is generated by the database, so it should be null before persisting
        assertNull(attendeeEntity.getId(), "ID should be null before persisting");
    }

    @Test
    public void testGetEmail() {
        String email = "aragorn@arnor.gov";
        AttendeeEntity attendeeEntity = new AttendeeEntity(email);

        assertEquals(email, attendeeEntity.getEmail(), "Email should match");
    }

    @Test
    public void testToString() {
        String email = "aragorn@arnor.gov";
        AttendeeEntity attendeeEntity = new AttendeeEntity(email);

        String expectedToString = "AttendeeEntity{id=null, email='aragorn@arnor.gov'}";
        assertEquals(expectedToString, attendeeEntity.toString(), "toString() should match expected format");
    }
}